In [2]:
import pandas as pd

df = pd.read_csv("../data/processed/cleaned_retail.csv")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [3]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [4]:
df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"]
)

In [5]:
snapshot_date = (
    df["InvoiceDate"].max()
    + pd.Timedelta(days=1)
)

print(snapshot_date)

2011-12-10 12:50:00

In [6]:
rfm = df.groupby(
    "CustomerID"
).agg({
    "InvoiceDate":
    lambda x:
    (snapshot_date - x.max()).days,

    "InvoiceNo":
    "nunique",

    "Revenue":
    "sum"
})

In [7]:
rfm.columns = [
    "Recency",
    "Frequency",
    "Monetary"
]

rfm.head()

            Recency  Frequency  Monetary
CustomerID
12346.0         326          2      0.00
12347.0           2          7   4310.00
12348.0          75          4   1797.24
12349.0          19          1   1757.55
12350.0         310          1    334.40

In [8]:

rfm.describe()

           Recency    Frequency       Monetary
count  4372.000000  4372.000000    4372.000000
mean     92.047118     5.075480    1893.531433
std     100.765435     9.338754    8218.696204
min       1.000000     1.000000   -4287.630000
25%      17.000000     1.000000     291.795000
50%      50.000000     3.000000     644.070000
75%     143.000000     5.000000    1608.335000
max     374.000000   248.000000  279489.020000

In [9]:
rfm.to_csv("../data/processed/rfm_customers.csv")